### ISSUE TITLE
ImportError: cannot import name 'autojit' from 'numba' 

### ISSUE THREAD

**Issue by deepanshu-nickelfox** [brohrer/lodgepole#1]

**Comment by brohrer** [comment]
Thanks for calling this out @deepanshu-nickelfox ! There was a breaking change in numba that deprecated the autojit decorator. 
The repo has also been relocated from GitHub to GitLab. The current version of the repo at GitLab has the fix in place: https://gitlab.com/brohrer/lodgepole/-/blob/main/lodgepole/image_tools.py

**Comment by deepanshu-nickelfox** [comment]
ohk Thank you for replying Mr @brohrer
